// Version awareness. The release image bakes QUICKDDEVPREVIEWS_VERSION at CI
// build time (.github/workflows/release.yml, Dockerfile prod ENV); anything
// else (dev, local builds) reports 'dev' and never offers updates.

export const RELEASE_TAG_RE = /^v\d+\.\d+\.\d+$/

const REPO = 'mandrasch/quick-ddev-previews'
const CACHE_MS = 60 * 60 * 1000

export function currentVersion(): string {
  return process.env.QUICKDDEVPREVIEWS_VERSION || 'dev'
}

let cache: { value: string | null, fetchedAt: number } | null = null

// The latest published release tag, from GitHub's releases/latest (which only
// sees actual Releases, exactly what the release workflow creates). Fetched
// lazily on demand, unauthenticated (60 req/h is plenty behind the 1h cache).
// On fetch failure the stale value (or null) is returned and the failure is
// cached too, so a GitHub outage can't stall every /api/system call.
export async function latestVersion(): Promise<string | null> {
  if (cache && Date.now() - cache.fetchedAt < CACHE_MS) return cache.value
  try {
    const res = await $fetch<{ tag_name?: string }>(
      `https://api.github.com/repos/${REPO}/releases/latest`,
      { timeout: 5000 },
    )
    const tag = res.tag_name && RELEASE_TAG_RE.test(res.tag_name) ? res.tag_name : null
    cache = { value: tag, fetchedAt: Date.now() }
  }
  catch {
    cache = { value: cache?.value ?? null, fetchedAt: Date.now() }
  }
  return cache.value
}

export interface Release {
  tag: string
  /** The release body: a plain commit-subject list, one "- subject" per line
   *  (generated by .github/workflows/release.yml). Rendered as text. */
  notes: string
  publishedAt: string | null
}

let releasesCache: { value: Release[], fetchedAt: number } | null = null

// The published changelog: recent releases with their notes, newest first.
// Same fetch contract as latestVersion(): unauthenticated, 1h cache, failures
// cached too (stale list or [] instead of a stalled request).
export async function listReleases(): Promise<Release[]> {
  if (releasesCache && Date.now() - releasesCache.fetchedAt < CACHE_MS) return releasesCache.value
  try {
    const res = await $fetch<{ tag_name?: string, body?: string, published_at?: string, draft?: boolean, prerelease?: boolean }[]>(
      `https://api.github.com/repos/${REPO}/releases?per_page=20`,
      { timeout: 5000 },
    )
    const releases = res
      .filter(r => r.tag_name && RELEASE_TAG_RE.test(r.tag_name) && !r.draft && !r.prerelease)
      .map(r => ({ tag: r.tag_name!, notes: (r.body ?? '').trim(), publishedAt: r.published_at ?? null }))
    releasesCache = { value: releases, fetchedAt: Date.now() }
  }
  catch {
    releasesCache = { value: releasesCache?.value ?? [], fetchedAt: Date.now() }
  }
  return releasesCache.value
}

// The RUNNING version may also be a pre-release (installed via install.sh's
// QUICKDDEVPREVIEWS_REF); candidates stay strictly stable, so a pre-release is
// never offered, only left behind.
const CURRENT_TAG_RE = /^v(\d+)\.(\d+)\.(\d+)(-.+)?$/

// Strict numeric compare of two release tags. The candidate must be a stable
// release tag; the current version may be a pre-release, which its own stable
// release (same version triplet) supersedes. False whenever a side matches
// neither shape (dev builds never see an update offer).
export function isNewerVersion(candidate: string, current: string): boolean {
  if (!RELEASE_TAG_RE.test(candidate)) return false
  const cur = current.match(CURRENT_TAG_RE)
  if (!cur) return false
  const a = candidate.slice(1).split('.').map(Number)
  const b = [Number(cur[1]), Number(cur[2]), Number(cur[3])]
  for (let i = 0; i < 3; i++) {
    if (a[i]! !== b[i]!) return a[i]! > b[i]!
  }
  return Boolean(cur[4])
}
